version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dirhamy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dirhamy
    ports:
      - "5432:5432"
    volumes:
      # ðŸ”¹ Bind Mount pour persister la DB sur la machine
      - ./docker-data/postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      args:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/dirhamy
    container_name: dirhamy-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dirhamy
      PORT: "3000"
      JWT_SECRET: anas
      REFRESH_TOKEN_SECRET: anas
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      # ðŸ”¹ Bind Mount du code backend (hot reload)
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "
        echo 'Waiting for Postgres...' &&
        until pg_isready -h db -p 5432 -U postgres; do
          sleep 1;
        done &&
        echo 'Postgres is ready' &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npm run dev
      "

  frontend:
    build:
      context: ./frontend
    container_name: dirhamy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      # Bind Mount frontend 
      - ./frontend:/usr/share/nginx/html

