version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dirhamy-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dirhamy
    ports:
      - "5431:5432"
    volumes:
      - dirhamy-pgdata:/var/lib/postgresql/data

  backend:
    env_file:
      - ./backend/.env
    build:
      context: ./backend
      args:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/dirhamy
    container_name: dirhamy-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/dirhamy
      PORT: "3000"

    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./backend:/app:Z
      - /app/node_modules
    command: >
      sh -c "
        echo 'Waiting for Postgres...' &&
        until pg_isready -h db -p 5432 -U postgres; do
          sleep 1;
        done &&
        echo 'Postgres is ready' &&
        npx prisma migrate deploy &&
        npx prisma generate &&
        npx prisma db seed &&
        npm run dev
      "

  frontend:
    build:
      context: ./frontend
    container_name: dirhamy-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html:Z
  
  redis:
    image: redis:7.4-alpine
    container_name: dirhamy-cache
    restart: always
    command: redis-server --requirepass anas1122
    ports:
      - "6379:6379"
    volumes:
      - dirhamy-redisdata:/data
volumes:
  dirhamy-pgdata:
  dirhamy-redisdata: